# Generated by Django 6.0.6 on 2026-06-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='subjects',
            new_name='subject',
        ),
    ]
